# Generated by Django 4.2.1 on 2023-05-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to=settings.AUTH_USER_MODEL),
        ),
    ]
