# Generated by Django 4.2.1 on 2023-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_pollmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
