# Generated by Django 4.2.1 on 2023-05-31 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_remove_pollmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='question',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9А-ЯҐЄІЇа-яєії !?.-()~#№$*+=,,-]{1,150}$', 'only letters min 2 max 150 ch')]),
        ),
    ]
