# Generated by Django 4.2.1 on 2023-06-03 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_pollmodel_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pollmodel',
            name='question',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9А-ЯҐЄІЇа-яєії !?.()~#№$*+=,,-]{1,150}$', 'only letters min 2 max 150 ch')]),
        ),
    ]
