# Generated by Django 4.2.1 on 2023-06-15 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meter', '0007_standardmetertypemodel'),
        ('payment_for_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_meter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_payment', to='meter.standardmetertypemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'standard_payment',
            },
        ),
    ]
