# Generated by Django 4.2.1 on 2023-06-07 14:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.upload_reading_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{6}$', 'serial number must contain 6 characters or digits with no space')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meter',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MeterTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specify', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'meter_type',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MeterReadingsPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_reading_service.upload_to)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meter.metermodel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meter_readings_photo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='metermodel',
            name='meter_specify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='meter.metertypemodel'),
        ),
    ]
