# Generated by Django 4.2.1 on 2023-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0003_rename_meterreadingsphotomodel_meterphotomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='metertypemodel',
            name='price',
            field=models.FloatField(default=5.0),
        ),
    ]
