# Generated by Django 4.2.1 on 2023-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0004_metertypemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metertypemodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
