# Generated by Django 4.2.1 on 2023-05-29 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.upload_advertisement_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9А-ЯҐЄІЇа-яєії -]{2,50}$', 'only letters min 2 max 50 ch')])),
                ('body', models.TextField()),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'invalid phone number Ex. 97 999 99 99 ')])),
                ('is_moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'advertisement',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisementPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_advertisement_service.upload_to)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advertisement.advertisementmodel')),
            ],
            options={
                'db_table': 'advertisement_photo',
                'ordering': ('id',),
            },
        ),
    ]
