# Generated by Django 4.2.1 on 2023-06-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeterReadingsPhotoModel',
            new_name='MeterPhotoModel',
        ),
    ]
